// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {syscall} from '../models';

export function DownloadAndExtractZip(arg1:string):Promise<string>;

export function DownloadAndLaunchHabbo():Promise<void>;

export function EmbedHabboWindow(arg1:syscall.Handle):Promise<void>;

export function HandleResize():Promise<void>;

export function LaunchAndEmbedHabbo():Promise<string>;

export function LaunchHabbo():Promise<void>;

export function OnResize(arg1:number,arg2:number):Promise<void>;

export function Quit():Promise<void>;

export function RunExecutable(arg1:string):Promise<void>;

export function UpdateHabboWindowPosition(arg1:syscall.Handle):Promise<void>;

export function WaitForHabboWindow():Promise<void>;
