// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureRoom() {
  return window['go']['main']['App']['CaptureRoom']();
}

export function DownloadAndExtractZip(arg1) {
  return window['go']['main']['App']['DownloadAndExtractZip'](arg1);
}

export function DownloadAndLaunchHabbo() {
  return window['go']['main']['App']['DownloadAndLaunchHabbo']();
}

export function EmbedHabboWindow(arg1) {
  return window['go']['main']['App']['EmbedHabboWindow'](arg1);
}

export function HandleInventoryUpdate() {
  return window['go']['main']['App']['HandleInventoryUpdate']();
}

export function HandleResize() {
  return window['go']['main']['App']['HandleResize']();
}

export function LaunchAndEmbedHabbo() {
  return window['go']['main']['App']['LaunchAndEmbedHabbo']();
}

export function LaunchHabbo() {
  return window['go']['main']['App']['LaunchHabbo']();
}

export function OnResize(arg1, arg2) {
  return window['go']['main']['App']['OnResize'](arg1, arg2);
}

export function PickupItems(arg1) {
  return window['go']['main']['App']['PickupItems'](arg1);
}

export function PlaceItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['PlaceItem'](arg1, arg2, arg3);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RunExecutable(arg1) {
  return window['go']['main']['App']['RunExecutable'](arg1);
}

export function StartInventoryScanning() {
  return window['go']['main']['App']['StartInventoryScanning']();
}

export function UpdateHabboWindowPosition(arg1) {
  return window['go']['main']['App']['UpdateHabboWindowPosition'](arg1);
}

export function UpdateInventoryDisplay() {
  return window['go']['main']['App']['UpdateInventoryDisplay']();
}

export function WaitForHabboWindow() {
  return window['go']['main']['App']['WaitForHabboWindow']();
}
