// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAndExtractZip(arg1) {
  return window['go']['main']['App']['DownloadAndExtractZip'](arg1);
}

export function DownloadAndLaunchHabbo() {
  return window['go']['main']['App']['DownloadAndLaunchHabbo']();
}

export function EmbedHabboWindow(arg1) {
  return window['go']['main']['App']['EmbedHabboWindow'](arg1);
}

export function HandleResize() {
  return window['go']['main']['App']['HandleResize']();
}

export function LaunchAndEmbedHabbo() {
  return window['go']['main']['App']['LaunchAndEmbedHabbo']();
}

export function LaunchHabbo() {
  return window['go']['main']['App']['LaunchHabbo']();
}

export function OnResize(arg1, arg2) {
  return window['go']['main']['App']['OnResize'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RunExecutable(arg1) {
  return window['go']['main']['App']['RunExecutable'](arg1);
}

export function UpdateHabboWindowPosition(arg1) {
  return window['go']['main']['App']['UpdateHabboWindowPosition'](arg1);
}

export function WaitForHabboWindow() {
  return window['go']['main']['App']['WaitForHabboWindow']();
}
